# Phase-1 E1.1 — obs-ablation training (3 tasks × 2 methods × 3 modes = 18 runs)
# AMASS_DATA_DIR=/home/ap2322/Documents/CMU/CMU/

MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/reach_target_single bodyslam=off seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-reach_target_single-bsoff-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","reach_target_single","bs-off"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/reach_target_single bodyslam=oracle seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-reach_target_single-bsoracle-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","reach_target_single","bs-oracle"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/reach_target_single bodyslam=noisy seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-reach_target_single-bsnoisy-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","reach_target_single","bs-noisy"]'

MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/dishwasher_close bodyslam=off seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-dishwasher_close-bsoff-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","dishwasher_close","bs-off"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/dishwasher_close bodyslam=oracle seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-dishwasher_close-bsoracle-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","dishwasher_close","bs-oracle"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/dishwasher_close bodyslam=noisy seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-dishwasher_close-bsnoisy-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","dishwasher_close","bs-noisy"]'

MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/drawers_open_all bodyslam=off seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-drawers_open_all-bsoff-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","drawers_open_all","bs-off"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/drawers_open_all bodyslam=oracle seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-drawers_open_all-bsoracle-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","drawers_open_all","bs-oracle"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=dp_pixel_safety_bigym env=safety_bigym/drawers_open_all bodyslam=noisy seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-dp-drawers_open_all-bsnoisy-s0 '+wandb.tags=["phase-1","obs-ablation","train","dp","drawers_open_all","bs-noisy"]'

MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/reach_target_single bodyslam=off seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-reach_target_single-bsoff-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","reach_target_single","bs-off"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/reach_target_single bodyslam=oracle seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-reach_target_single-bsoracle-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","reach_target_single","bs-oracle"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/reach_target_single bodyslam=noisy seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-reach_target_single-bsnoisy-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","reach_target_single","bs-noisy"]'

MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/dishwasher_close bodyslam=off seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-dishwasher_close-bsoff-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","dishwasher_close","bs-off"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/dishwasher_close bodyslam=oracle seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-dishwasher_close-bsoracle-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","dishwasher_close","bs-oracle"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/dishwasher_close bodyslam=noisy seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-dishwasher_close-bsnoisy-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","dishwasher_close","bs-noisy"]'

MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/drawers_open_all bodyslam=off seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-drawers_open_all-bsoff-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","drawers_open_all","bs-off"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/drawers_open_all bodyslam=oracle seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-drawers_open_all-bsoracle-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","drawers_open_all","bs-oracle"]'
MUJOCO_GL=egl PYOPENGL_PLATFORM=egl /home/ap2322/Documents/safety_bigym/venv/bin/python train_safety.py launch=act_pixel_safety_bigym env=safety_bigym/drawers_open_all bodyslam=noisy seed=0 save_snapshot=true wandb.use=true wandb.name=phase1-train-act-drawers_open_all-bsnoisy-s0 '+wandb.tags=["phase-1","obs-ablation","train","act","drawers_open_all","bs-noisy"]'

