"""
SafetyBiGymEnv - BiGym Environment with ISO 15066 Safety Monitoring

Wraps any BiGym task to add:
- SMPL-H human that follows AMASS motion with IK disruption
- ISO 15066 safety monitoring (SSM + PFL)
- Per-sub-step force capture for accurate PFL checking
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Optional, Type, List, Dict
from dataclasses import asdict

import numpy as np
import mujoco
from lxml import etree

from bigym.bigym_env import BiGymEnv, PHYSICS_DT
from bigym.action_modes import ActionMode
from bigym.robots.robot import Robot

from safety_bigym.config import (
    SafetyConfig,
    HumanConfig,
    SSMConfig,
    get_spawn_positions,
)
from safety_bigym.safety import (
    ISO15066Wrapper,
    SafetyInfo,
    ContactInfo,
)
from safety_bigym.human import (
    HumanController,
    PDController,
    PDGains,
    TrajectoryPlanner,
    TrajectoryConfig,
    TrajectoryType,
)
from safety_bigym.human import g1_spec
from safety_bigym.scenarios import (
    ScenarioSampler,
    ScenarioParams,
    ParameterSpace,
)
from safety_bigym.scenarios.disruption_types import DisruptionType
from safety_bigym.scenarios.coworker_behavior import CoworkerArmController

logger = logging.getLogger(__name__)


class SafetyBiGymEnv(BiGymEnv):
    """
    BiGym environment with ISO 15066 safety monitoring.
    
    Extends BiGym to add:
    - SMPL-H human spawned in the scene
    - Human motion from AMASS with IK-based disruption
    - SSM (Speed and Separation Monitoring)
    - PFL (Power and Force Limiting) with per-sub-step capture
    
    The safety information is returned in info["safety"] dict containing:
    - ssm_violation: bool
    - pfl_violation: bool
    - ssm_margin: float (positive = safe, negative = violation)
    - max_contact_force: float
    - contact_region: str (body part if contact)
    - contact_type: str ("transient" or "quasi_static")
    """
    
    # Path to the coworker body asset. The "human" is now a Unitree G1
    # humanoid (assets/g1_human_body.xml, generated by
    # scripts/build_g1_human_body.py); it keeps the human_* naming because it
    # plays the same coworker-obstacle role the SMPL-H human used to.
    HUMAN_ASSET_PATH = Path(__file__).parent.parent / "assets" / "g1_human_body.xml"
    HUMAN_BODY_PATH = Path(__file__).parent.parent / "assets" / "g1_human_body.xml"
    
    def __init__(
        self,
        action_mode: ActionMode,
        safety_config: Optional[SafetyConfig] = None,
        human_config: Optional[HumanConfig] = None,
        scenario_sampler: Optional[ScenarioSampler] = None,
        inject_human: bool = True,
        **kwargs
    ):
        """
        Initialize SafetyBiGymEnv.
        
        Args:
            action_mode: BiGym action mode for robot control
            safety_config: ISO 15066 safety parameters
            human_config: Human spawn and motion configuration
            scenario_sampler: Sampler for diverse scenarios (uses default if None)
            inject_human: Whether to inject human into scene (set False for testing)
            **kwargs: Additional arguments passed to BiGymEnv
        """
        self.safety_config = safety_config or SafetyConfig()
        self.human_config = human_config or HumanConfig()
        self._inject_human = inject_human
        
        # Human body IDs (set during injection)
        self._human_pelvis_id: Optional[int] = None
        # Pelvis is a mocap body; this is its index into data.mocap_pos /
        # data.mocap_quat. None when no human is injected.
        self._human_pelvis_mocapid: Optional[int] = None
        
        # If injecting human, we need to do it BEFORE parent __init__ creates robot
        # because robot binds to physics and changing model after breaks bindings.
        # We'll use a temporary custom model path.
        if inject_human and self.HUMAN_BODY_PATH.exists():
            # Create merged world XML
            self._merged_model_path = self._create_merged_world()
            # Temporarily override class model path
            original_model_path = self._MODEL_PATH
            self.__class__._MODEL_PATH = Path(self._merged_model_path)
            try:
                super().__init__(action_mode=action_mode, **kwargs)
            finally:
                self.__class__._MODEL_PATH = original_model_path
            self._setup_human_indices()
        else:
            # Normal init without human
            super().__init__(action_mode=action_mode, **kwargs)
        
        # Scenario sampler
        if scenario_sampler is None:
            param_space = ParameterSpace(
                clip_paths=self.human_config.motion_clip_paths,
            )
            self.scenario_sampler = ScenarioSampler(
                parameter_space=param_space,
                motion_dir=self.human_config.motion_clip_dir,
            )
        else:
            self.scenario_sampler = scenario_sampler
        
        # Current scenario (set on reset)
        self._current_scenario: Optional[ScenarioParams] = None
        self._coworker_controller: Optional[CoworkerArmController] = None

        # Human components (initialized after human injection)
        self.human_controller: Optional[HumanController] = None
        self.safety_wrapper: Optional[ISO15066Wrapper] = None
        
        # Per-step safety tracking
        self._step_contacts: List[ContactInfo] = []
        self._step_safety_info: Optional[SafetyInfo] = None
        self._prev_human_pos: Optional[np.ndarray] = None
        
        # Spawn positions for this task
        self._spawn_positions = get_spawn_positions(self.task_name)
        if self.human_config.spawn_positions:
            self._spawn_positions = self.human_config.spawn_positions
        
        # Robot geom names for collision detection
        self._robot_geom_names: List[str] = []
        self._collect_robot_geoms()

        # Wire up the human<->{robot, floor} collision channel (bit 1). The
        # human MJCF uses contype/conaffinity=2 so scene props (dishwasher,
        # cabinets) on the default bit-0 channel never see the human.
        if self._inject_human:
            self._configure_collision_bits()

        # Initialize safety wrapper and human controller
        if self._inject_human:
            self._init_safety_wrapper()
            self._init_human_controller()
    
    def _create_merged_world(self) -> str:
        """
        Create a merged world XML that includes the human body.
        Returns path to the temporary merged XML file.
        """
        import tempfile
        from lxml import etree
        
        # Read world XML
        world_xml = etree.parse(str(self._MODEL_PATH))
        world_root = world_xml.getroot()
        
        # Read human body XML
        human_xml = etree.parse(str(self.HUMAN_BODY_PATH))
        human_root = human_xml.getroot()
        
        # Find worldbody in both
        world_worldbody = world_root.find(".//worldbody")
        human_worldbody = human_root.find(".//worldbody")
        
        # Copy human body hierarchy to world
        import copy
        for body in human_worldbody:
            world_worldbody.append(copy.deepcopy(body))
        
        # Copy human defaults (under class prefix to avoid conflicts)
        human_default = human_root.find(".//default")
        if human_default is not None:
            world_default = world_root.find("default")
            if world_default is None:
                world_default = etree.SubElement(world_root, "default")
            for child in human_default:
                world_default.append(copy.deepcopy(child))
        
        # Copy human actuators
        human_actuators = human_root.find(".//actuator")
        if human_actuators is not None:
            world_actuator = world_root.find("actuator")
            if world_actuator is None:
                world_actuator = etree.SubElement(world_root, "actuator")
            for act in human_actuators:
                world_actuator.append(copy.deepcopy(act))

        # Copy human assets (G1 meshes/materials). The merged XML is written to
        # a temp dir, so the body file's relative <compiler meshdir> won't
        # resolve — rewrite every mesh `file` to an absolute path. Mesh and
        # material names are already `g1_`-prefixed by the generator so they
        # can't collide with BiGym scene asset names.
        human_asset = human_root.find(".//asset")
        if human_asset is not None:
            human_compiler = human_root.find("compiler")
            meshdir = human_compiler.get("meshdir") if human_compiler is not None else ""
            mesh_base = (self.HUMAN_BODY_PATH.parent / meshdir).resolve()
            world_asset = world_root.find("asset")
            if world_asset is None:
                world_asset = etree.SubElement(world_root, "asset")
            for node in human_asset:
                node = copy.deepcopy(node)
                if node.tag == "mesh" and node.get("file"):
                    node.set("file", str(mesh_base / node.get("file")))
                world_asset.append(node)
        
        # Note: BiGym attaches the H1 robot programmatically after model
        # load (via mojo), so the merged XML never contains robot geoms
        # — there is no compile-time hook to inject `<contact><pair>`
        # entries between human and robot. Pair-injection workarounds
        # for the BiGym-specific human<->robot collision suppression
        # need to happen via a different mechanism (TBD).
        with tempfile.NamedTemporaryFile(mode='w', suffix='.xml', delete=False) as f:
            f.write(etree.tostring(world_root, encoding="unicode"))
            return f.name

    def _setup_human_indices(self):
        """Find human body/joint indices after model is loaded."""
        model = self._mojo.model

        # Find the mocap root (G1 pelvis)
        self._human_pelvis_id = mujoco.mj_name2id(
            model, mujoco.mjtObj.mjOBJ_BODY, g1_spec.PELVIS_BODY
        )

        # Pelvis is a mocap body; resolve its index into data.mocap_pos /
        # data.mocap_quat. body_mocapid is -1 for non-mocap bodies.
        if self._human_pelvis_id is not None and self._human_pelvis_id >= 0:
            mid = int(model.body_mocapid[self._human_pelvis_id])
            self._human_pelvis_mocapid = mid if mid >= 0 else None

        self._setup_human_ssm_bodies()

        logger.info(
            f"Human indices: pelvis_id={self._human_pelvis_id}, "
            f"pelvis_mocapid={self._human_pelvis_mocapid}, "
            f"ssm_bodies={len(self._human_body_ids)}"
        )

    _HUMAN_SSM_BODY_NAMES = g1_spec.SSM_BODY_NAMES

    def _setup_human_ssm_bodies(self):
        """Collect G1 body IDs used for closest-joint SSM (T0.2)."""
        model = self._mojo.model
        self._human_body_ids: List[int] = []
        self._human_body_names: List[str] = []
        for name in self._HUMAN_SSM_BODY_NAMES:
            bid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, name)
            if bid >= 0:
                self._human_body_ids.append(bid)
                self._human_body_names.append(name)
    
    def _collect_robot_geoms(self):
        """Collect robot geom names for safety wrapper."""
        # Get all geoms from robot
        model = self._mojo.model
        for i in range(model.ngeom):
            name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, i)
            if name and self._is_robot_geom(name):
                self._robot_geom_names.append(name)
        logger.debug(f"Collected {len(self._robot_geom_names)} robot geoms")
    
    def _is_robot_geom(self, name: str) -> bool:
        """Check if geom belongs to robot."""
        # Exclude human collision geoms (they end with _col)
        if name.endswith("_col"):
            return False

        # Robot geoms typically have patterns like "h1/*", etc.
        # Only match h1/ prefix to avoid matching human body parts
        robot_patterns = ["h1/", "robotiq"]
        name_lower = name.lower()
        return any(p in name_lower for p in robot_patterns)

    # Two-bit cross-paired channel for human<->{robot,floor} collisions.
    # Human geoms emit on _HUMAN_EMIT and accept _ROBOT_EMIT; robot/floor
    # geoms get the cross set OR'd onto their existing bits. This keeps
    # human<->robot pairs eligible while making human<->human pairs
    # ineligible (their cross is `(emit & accept) = 0`).
    _HUMAN_EMIT_BIT = 0b010   # bit 1
    _ROBOT_EMIT_BIT = 0b100   # bit 2

    def _configure_collision_bits(self) -> None:
        """Wire up the cross-paired human<->{robot,floor} collision channel
        and disable human self-collision.

        The SMPL human MJCF puts every `_col` geom on bit 1 for both
        contype and conaffinity. With matching bits on both sides, every
        pair of human geoms is a collision candidate and produces wildly
        non-physical self-overlap forces (Torso/Chest at 220 kN). These
        dominate `data.contact` and crowd out human<->robot pairs.

        MuJoCo's contact-eligibility rule requires BOTH
        `(geom1.contype & geom2.conaffinity) != 0` AND
        `(geom2.contype & geom1.conaffinity) != 0`. So we can't simply
        zero one side — that would block human<->robot too. Instead we
        use two bits:

            human  contype = bit 1, conaffinity = bit 2
            robot  contype |= bit 2, conaffinity |= bit 1
            floor  contype |= bit 2, conaffinity |= bit 1

        human<->human cross = (bit1 & bit2) = 0 -> ineligible.
        human<->robot      = (bit1 & bit1) AND (bit2 & bit2), both
                              non-zero -> eligible.

        Robot's original bit-0 channel is preserved so robot<->robot
        self-collision keeps working. Scene geoms (dishwasher, cabinets,
        walls) stay on bit 0 only -> human passes through them.
        """
        model = self._mojo.model
        h_emit = self._HUMAN_EMIT_BIT
        r_emit = self._ROBOT_EMIT_BIT
        skip_floor = bool(getattr(
            self.safety_config, "disable_human_floor_collision", False
        ))
        promoted = 0
        floors_skipped = 0
        humans_repaired = 0
        for gid in range(model.ngeom):
            name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, gid)
            if not name:
                continue
            # Skip geoms that are disabled from collision entirely (visual-only).
            if model.geom_contype[gid] == 0 and model.geom_conaffinity[gid] == 0:
                continue
            if name.endswith("_col"):
                # Human collision geom: emit on bit 1, accept bit 2.
                model.geom_contype[gid] = h_emit
                model.geom_conaffinity[gid] = r_emit
                humans_repaired += 1
                continue
            is_robot = self._is_robot_geom(name)
            is_floor = name == "floor" or name.endswith("/floor") or "ground" in name.lower()
            if is_floor and skip_floor:
                # G1 bisection: leave the floor on its default bit-0 channel,
                # so human <-> floor contacts are filtered out by MuJoCo's
                # contype/conaffinity intersection. Robot <-> floor is
                # unaffected (robot's bit-0 channel still overlaps the floor's).
                floors_skipped += 1
                continue
            if is_robot or is_floor:
                # Cross-pair: emit on bit 2 (so human accepts), accept bit 1
                # (so the human's emit reaches us). OR'd onto existing bits.
                model.geom_contype[gid] = int(model.geom_contype[gid]) | r_emit
                model.geom_conaffinity[gid] = int(model.geom_conaffinity[gid]) | h_emit
                promoted += 1
        logger.info(
            f"Promoted {promoted} geoms onto human collision channel "
            f"(human_emit=bit1, robot_emit=bit2); reset {humans_repaired} "
            "human collision geoms onto the cross-paired channel."
            + (f"; skipped {floors_skipped} floor geoms (disable_human_floor_collision=True)"
               if floors_skipped else "")
        )

    # Backwards-compat alias: old code/tests may still read this constant.
    _HUMAN_CHANNEL_BIT = _HUMAN_EMIT_BIT
    

    
    def _init_safety_wrapper(self):
        """Initialize ISO 15066 safety wrapper."""
        self.safety_wrapper = ISO15066Wrapper(
            model=self._mojo.model,
            data=self._mojo.data,
            ssm_config=self.safety_config.ssm,
            human_geom_suffix="_col",
        )
        
        # Register robot geoms
        for geom_name in self._robot_geom_names:
            try:
                self.safety_wrapper.add_robot_geom(geom_name)
            except ValueError:
                pass  # Geom not found in merged model
        
        # Register fixture geoms (floor, walls, tables, etc.)
        fixture_patterns = ["floor", "wall", "table", "counter", "cabinet"]
        model = self._mojo.model
        for i in range(model.ngeom):
            name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, i)
            if name:
                name_lower = name.lower()
                if any(p in name_lower for p in fixture_patterns):
                    try:
                        self.safety_wrapper.add_fixture_geom(name)
                    except ValueError:
                        pass
        
        logger.info("Safety wrapper initialized")
    
    def _init_human_controller(self):
        """Initialize human motion controller."""
        gains = PDGains(
            kp=self.human_config.pd_kp,
            kd=self.human_config.pd_kd,
        )
        
        self.human_controller = HumanController(
            model=self._mojo.model,
            data=self._mojo.data,
            gains=gains,
        )
        
        logger.info("Human controller initialized")
    
    def _position_human(self, spawn_config: Dict[str, Any]):
        """
        Position human at spawn location.
        
        Args:
            spawn_config: Dict with 'pos' and 'yaw' keys
        """
        if self._human_pelvis_mocapid is None:
            return

        pos = np.array(spawn_config.get("pos", [2.0, 0.0, 0.0]))
        yaw = spawn_config.get("yaw", 0.0)

        # Fixed standing pelvis height for the G1 (no AMASS clip any more).
        initial_z = g1_spec.STANDING_PELVIS_Z

        # Tell the controller where the coworker spawned (XY anchor for the
        # scripted trajectory).
        if self.human_controller is not None:
            self.human_controller.set_root_offset(pos)

        quat = np.array([
            np.cos(yaw / 2),
            0,
            0,
            np.sin(yaw / 2),
        ])
        mid = self._human_pelvis_mocapid
        self._mojo.data.mocap_pos[mid] = [pos[0], pos[1], initial_z]
        self._mojo.data.mocap_quat[mid] = quat

        # Forward kinematics to update body positions and propagate the
        # new mocap pose into data.xpos / geom_xpos so the next collision
        # detection sees the correct geometry.
        mujoco.mj_forward(self._mojo.model, self._mojo.data)
    
    def reset(self, *, seed: Optional[int] = None, options: Optional[dict] = None):
        """Reset environment with new scenario."""
        # Parent reset (resets robot and world)
        obs, info = super().reset(seed=seed, options=options)
        
        if not self._inject_human:
            return obs, info
        
        # Sample new scenario
        scenario_seed = seed if seed is not None else np.random.randint(2**31)
        self._current_scenario = self.scenario_sampler.sample_scenario(scenario_seed)
        
        # Reset human controller
        if self.human_controller is not None:
            self.human_controller.reset()
            
            # Load motion clip
            if self._current_scenario.clip_path:
                # Build full path from motion_clip_dir + relative clip path
                if self.human_config.motion_clip_dir:
                    full_clip_path = str(Path(self.human_config.motion_clip_dir) / self._current_scenario.clip_path)
                else:
                    full_clip_path = self._current_scenario.clip_path
                    
                try:
                    self.human_controller.load_clip(full_clip_path)
                except Exception as e:
                    logger.warning(f"Failed to load clip: {e}")
            
            # Set scenario parameters (ScenarioParams is now unified)
            self.human_controller.set_scenario(self._current_scenario)
        
        # Compute spawn position from scenario parameters
        # approach_angle: 0° = in front (+X), 90° = left (+Y), etc.
        angle_rad = np.deg2rad(self._current_scenario.approach_angle)
        dist = self._current_scenario.spawn_distance
        
        # Robot is at approximately (0, 0) — spawn on a circle around it
        spawn_x = dist * np.cos(angle_rad)
        spawn_y = dist * np.sin(angle_rad)
        
        # Yaw to face toward robot (opposite of spawn direction)
        face_robot_yaw = np.arctan2(-spawn_y, -spawn_x)
        
        spawn_config = {
            "pos": [spawn_x, spawn_y, 0.0],
            "yaw": face_robot_yaw,
        }
        self._position_human(spawn_config)
        
        # --- Create trajectory planner from scenario params ---
        trajectory_type_map = {
            "PASS_BY": TrajectoryType.PASS_BY,
            "APPROACH_LOITER_DEPART": TrajectoryType.APPROACH_LOITER_DEPART,
            "ARC": TrajectoryType.ARC,
            "STATIONARY": TrajectoryType.STATIONARY,
            "COWORKER_PATROL": TrajectoryType.COWORKER_PATROL,
        }
        traj_type_str = getattr(self._current_scenario, 'trajectory_type', 'PASS_BY')
        traj_type = trajectory_type_map.get(traj_type_str, TrajectoryType.PASS_BY)
        
        traj_config = TrajectoryConfig(
            trajectory_type=traj_type,
            robot_pos=np.array([0.0, 0.0]),  # Robot at origin
            spawn_pos=np.array([spawn_x, spawn_y]),
            approach_yaw=face_robot_yaw,
            pass_by_offset=getattr(self._current_scenario, 'pass_by_offset', 1.0),
            pass_by_side=getattr(self._current_scenario, 'pass_by_side', 1),
            closest_approach=getattr(self._current_scenario, 'closest_approach', 1.0),
            loiter_duration=getattr(self._current_scenario, 'loiter_duration', 2.0),
            departure_angle=getattr(self._current_scenario, 'departure_angle', 150.0),
            arc_radius=getattr(self._current_scenario, 'arc_radius', 1.5),
            arc_extent=getattr(self._current_scenario, 'arc_extent', 120.0),
            walk_speed=getattr(self._current_scenario, 'walk_speed', 1.2),
            patrol_near_loiter=getattr(
                self._current_scenario, 'patrol_near_loiter', 8.0
            ),
            patrol_away_loiter=getattr(
                self._current_scenario, 'patrol_away_loiter', 3.5
            ),
            patrol_away_distance=getattr(
                self._current_scenario, 'patrol_away_distance', 2.5
            ),
            patrol_excursions=getattr(
                self._current_scenario, 'patrol_excursions', 2
            ),
            patrol_near_distance_std=getattr(
                self._current_scenario, 'patrol_near_distance_std', 0.12
            ),
            patrol_near_distance_clip=getattr(
                self._current_scenario, 'patrol_near_distance_clip', 0.25
            ),
            # Drive patrol angle / distance sampling off the scenario
            # seed so the excursion layout is reproducible per-episode.
            patrol_seed=getattr(self._current_scenario, 'seed', None),
        )
        
        trajectory_planner = TrajectoryPlanner(traj_config)
        
        if self.human_controller is not None:
            self.human_controller.set_trajectory_planner(trajectory_planner)

        # Orient AMASS motion direction toward robot
        if self.human_controller is not None:
            self.human_controller.set_root_yaw(face_robot_yaw)

        # COWORKER drives the arm via a procedural state-machine callback
        # instead of AMASS playback during loiter. Other disruption types
        # have no IK callback wired today (their behaviour is unaffected).
        if (
            self.human_controller is not None
            and self._current_scenario.disruption_type == DisruptionType.COWORKER
        ):
            coworker = CoworkerArmController(
                self._mojo.model,
                self._mojo.data,
                self._current_scenario,
                np.random.default_rng(scenario_seed),
                rest_qpos=g1_spec.standing_qpos(self._mojo.model),
            )
            self.human_controller.set_ik_callback(coworker.make_callback())
            self._coworker_controller = coworker
        else:
            self._coworker_controller = None
        
        # Reset safety wrapper
        if self.safety_wrapper is not None:
            self.safety_wrapper.reset()
        
        # Clear per-step tracking
        self._step_contacts = []
        self._step_safety_info = None
        self._prev_human_pos = None
        
        # Add scenario info
        info["scenario"] = {
            "disruption_type": self._current_scenario.disruption_type.name,
            "trigger_time": self._current_scenario.trigger_time,
            "clip_path": self._current_scenario.clip_path,
            "trajectory_type": traj_type_str,
        }

        # Phase-1 contract: downstream wrappers (BodySLAMWrapper) expect
        # human_pos in info["safety"] at reset. The full SafetyInfo is
        # only computed on step, so emit just the pelvis xpos here.
        if self._human_pelvis_id is not None:
            if "safety" not in info:
                info["safety"] = {}
            info["safety"]["human_pos"] = list(
                self._mojo.data.xpos[self._human_pelvis_id].copy()
            )

        return obs, info
    
    def _step_mujoco_simulation(self, action):
        """
        Step physics with human control and safety monitoring.
        
        This overrides BiGym's method to:
        1. Update human PD targets before each sub-step
        2. Capture contact forces after each sub-step
        """
        if action.shape != self.action_space.shape:
            raise ValueError(
                f"Action shape mismatch: "
                f"expected {self.action_space.shape}, but got {action.shape}."
            )
        # Soft-clip rather than raise. RoboBase's RescaleFromTanhWithMinMax
        # produces actions in `[1.2*low, 1.2*high]` by design (margin lets
        # the policy explore beyond demo-observed action ranges); under RL
        # with exploration noise (DrQ-V2's stddev_schedule) the post-rescale
        # action can sit a few percent past `action_space.{low,high}`. BC
        # methods (ACT/DP) hug demo actions so this rarely fires for them.
        # Either way, crashing the env mid-rollout discards an expensive
        # rollout for a sub-millimetre overshoot — clip silently instead.
        if np.any(action < self.action_space.low) or np.any(
            action > self.action_space.high
        ):
            action = np.clip(
                action, self.action_space.low, self.action_space.high
            )
        
        # Clear per-step contacts
        self._step_contacts = []
        
        # Get robot state for IK (if human controller needs it)
        robot_state = self._get_robot_state()
        
        with self._env_health.track():
            for i in range(self._sub_steps_count):
                # 1. Update human controls BEFORE physics step
                if self.human_controller is not None:
                    self.human_controller.step(PHYSICS_DT, robot_state=robot_state)
                
                # 2. Apply robot action (BiGym's original logic)
                if i == 0:
                    self.action_mode.step(action)
                else:
                    self._mojo.step()
                
                mujoco.mj_rnePostConstraint(self._mojo.model, self._mojo.data)
                
                # 3. Capture forces AFTER physics step
                if self.safety_wrapper is not None:
                    substep_contacts = self.safety_wrapper.check_safety_substep()
                    self._step_contacts.extend(substep_contacts)
        
        # Aggregate safety info for this step
        self._aggregate_safety_info()
    
    # Candidate MuJoCo body names for CONTACT IK targets, in priority order.
    # Lookup is best-effort: missing names are silently dropped.
    _ROBOT_LINK_NAMES = {
        "ee": ["h1/right_hand", "h1/left_hand", "h1/right_wrist_link", "h1/left_wrist_link"],
        "right_forearm": ["h1/right_elbow_link", "h1/right_forearm", "h1/right_lower_arm_link"],
        "left_forearm": ["h1/left_elbow_link", "h1/left_forearm", "h1/left_lower_arm_link"],
        "torso": ["h1/torso_link", "h1/torso", "h1/chest_link"],
    }

    def _get_robot_state(self) -> Dict[str, Any]:
        """Get current robot state for IK computation."""
        state: Dict[str, Any] = {}

        # Robot pelvis / base position
        try:
            pelvis_pos = np.asarray(self._robot.pelvis.get_position(), dtype=float)
            state["robot_pos"] = pelvis_pos
            state["robot_base_pos"] = pelvis_pos
        except Exception:
            state["robot_pos"] = np.zeros(3)
            state["robot_base_pos"] = np.zeros(3)

        # End effector position
        ee_pos: Optional[np.ndarray] = None
        try:
            ee_pos = np.asarray(self._robot.get_ee_position(), dtype=float)
            state["ee_pos"] = ee_pos
        except Exception:
            pass

        # Per-link positions for CONTACT IK targeting
        link_pos: Dict[str, np.ndarray] = {}
        if ee_pos is not None:
            link_pos["ee"] = ee_pos
        model = self._mojo.model
        data = self._mojo.data
        for part, candidates in self._ROBOT_LINK_NAMES.items():
            if part in link_pos:
                continue
            for name in candidates:
                bid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, name)
                if bid >= 0:
                    link_pos[part] = data.xpos[bid].copy()
                    break
        if link_pos:
            state["link_pos"] = link_pos

        # Human pelvis position (CONTACT uses this to bias embed direction).
        if self._human_pelvis_id is not None:
            state["human_pelvis_pos"] = data.xpos[self._human_pelvis_id].copy()

        # Task-object position (best-effort): BiGym tasks expose the
        # manipulable through task-specific attribute names. Scan the
        # common ones in priority order — bona-fide manipulables first
        # (box / saucepan / cup / cube / plate / mug), then "list of N"
        # variants (cups[0], plates[0], ...), then the larger fixed
        # scene props the robot interacts with (dishwasher / cabinets).
        # If nothing matches, leave the key absent — the COWORKER
        # callback uses the EE as its target in that case.
        task_pos = self._lookup_task_object_pos()
        if task_pos is not None:
            state["task_object_pos"] = task_pos

        return state

    # Per-task manipulables, scanned in priority order: singletons first
    # (more specific), then list attributes (sampling [0]), then larger
    # fixed scene props. Keep these in priority order; the first hit wins.
    _TASK_OBJECT_ATTRS_SINGLE = (
        "box", "saucepan", "cup", "cube", "plate", "mug", "kettle", "pan",
    )
    _TASK_OBJECT_ATTRS_LIST = (
        "cups", "plates", "cubes", "boxes", "mugs", "cutlery", "items",
    )
    _TASK_OBJECT_ATTRS_SCENE = (
        "dishwasher", "cabinet_drawers", "cabinet_wall", "cabinet_base",
        "cabinet_door_left", "cabinet_door_right", "shelf", "tray",
    )

    def _scene_attrs_for_task(self) -> tuple:
        """Return the SCENE-attr scan order for workspace shaping.

        The default order in ``_TASK_OBJECT_ATTRS_SCENE`` is fine for most
        tasks but wrong for ``WallCupboardOpen/Close``: those tasks have
        BOTH ``cabinet_drawers`` (base counter, unused by the task) AND
        ``cabinet_wall`` (the wall cupboard, the actual target) attached to
        the env, and the static list picks ``cabinet_drawers`` first —
        which would pull the workspace shaping toward the wrong cabinet.

        Look up the task name and override the order for known cases.
        """
        name = (getattr(self, "task_name", "") or "").lower()
        if "wallcupboard" in name:
            return (
                "cabinet_wall", "cabinet_drawers", "cabinet_base",
                "cabinet_door_left", "cabinet_door_right",
                "dishwasher", "shelf", "tray",
            )
        return self._TASK_OBJECT_ATTRS_SCENE

    def _lookup_task_object_pos(self) -> Optional[np.ndarray]:
        # ReachTarget-style tasks: a list of TargetSphere objects.
        try:
            targets = getattr(self, "targets", None)
            if targets:
                return np.asarray(targets[0].body.get_position(), dtype=float)
        except Exception:
            pass

        for attr in self._TASK_OBJECT_ATTRS_SINGLE:
            obj = getattr(self, attr, None)
            if obj is None:
                continue
            pos = self._try_get_position(obj)
            if pos is not None:
                return pos

        for attr in self._TASK_OBJECT_ATTRS_LIST:
            seq = getattr(self, attr, None)
            if not seq:
                continue
            try:
                first = seq[0]
            except Exception:
                continue
            pos = self._try_get_position(first)
            if pos is not None:
                return pos

        for attr in self._scene_attrs_for_task():
            obj = getattr(self, attr, None)
            if obj is None:
                continue
            pos = self._try_get_position(obj)
            if pos is not None:
                return pos

        return None

    @staticmethod
    def _try_get_position(obj) -> Optional[np.ndarray]:
        """Best-effort wrapper around BiGym prop position accessors;
        different prop classes expose this on the prop itself, on a
        nested ``.body``, or as a ``.position`` attribute."""
        for accessor in (
            lambda o: o.get_position(),
            lambda o: o.body.get_position(),
            lambda o: o.position,
        ):
            try:
                pos = accessor(obj)
            except Exception:
                continue
            try:
                return np.asarray(pos, dtype=float).reshape(3)
            except Exception:
                continue
        return None
    
    def _aggregate_safety_info(self):
        """Aggregate sub-step contacts into step-level safety info.

        Closest-joint SSM (T0.2) + shared build_safety_info (T0.1)."""
        if self.safety_wrapper is None:
            self._step_safety_info = SafetyInfo()
            return

        robot_positions, robot_names, robot_vel = self._robot_ssm_state()
        human_positions, human_names, human_vel = self._human_ssm_state()

        # ssm_violation uses the worst-case ISO assumption (v_h = v_h_max);
        # ssm_violation_actual uses the observed human velocity. The robot
        # side passes its observed speed for both — SSMConfig has no v_r_max
        # so there is no "worst-case" robot value to substitute. See
        # docs/safety_metrics.md for the thesis-reporting roles.
        v_h_max = float(self.safety_config.ssm.v_h_max)
        self._step_safety_info = self.safety_wrapper.build_safety_info(
            contacts=self._step_contacts,
            robot_positions=robot_positions,
            robot_vel=robot_vel,
            human_positions=human_positions,
            human_vel=v_h_max,
            human_names=human_names,
            robot_names=robot_names,
            human_vel_actual=human_vel,
            robot_vel_actual=robot_vel,
        )
        return

    def _robot_ssm_state(self):
        """Positions (Nr,3), names, and max link speed for every robot geom
        registered on the safety wrapper. Falls back to pelvis-only."""
        model = self._mojo.model
        data = self._mojo.data
        names = []
        positions = []
        max_vel = 0.0
        for gid in sorted(self.safety_wrapper.robot_geoms):
            positions.append(data.geom_xpos[gid].copy())
            gname = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, gid)
            names.append(gname or f"geom_{gid}")
            body_id = int(model.geom_bodyid[gid])
            if body_id >= 0:
                linvel = float(np.linalg.norm(data.cvel[body_id, 3:6]))
                if linvel > max_vel:
                    max_vel = linvel
        if not positions:
            try:
                pos = np.asarray(self._robot.pelvis.get_position(), dtype=float)
                positions = [pos]
                names = ["h1/pelvis"]
                pid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "h1/pelvis")
                if pid >= 0:
                    max_vel = float(np.linalg.norm(data.cvel[pid, 3:6]))
            except Exception:
                positions = [np.zeros(3)]
                names = ["unknown"]
        return np.stack(positions), names, max_vel

    def _human_ssm_state(self):
        """Positions (Nh,3), names, and max body speed for every SMPL body we
        track. Max-over-bodies speed is ISO 15066\'s conservative reading."""
        data = self._mojo.data
        body_ids = getattr(self, "_human_body_ids", [])
        if not body_ids:
            if self._human_pelvis_id is not None:
                pos = data.xpos[self._human_pelvis_id].copy()
                return np.stack([pos]), [g1_spec.PELVIS_BODY], 0.0
            return np.zeros((1, 3)), ["unknown"], 0.0
        positions = [data.xpos[bid].copy() for bid in body_ids]
        names = list(self._human_body_names)
        max_vel = 0.0
        for bid in body_ids:
            linvel = float(np.linalg.norm(data.cvel[bid, 3:6]))
            if linvel > max_vel:
                max_vel = linvel
        # AMASS playback teleports qpos every sub-step, so MuJoCo's implicit
        # cvel = (qpos_new - qpos_old) / PHYSICS_DT can be absurdly large (tens
        # of m/s) and blows up S_p. ISO 15066 assumes a bounded walking human
        # anyway — cap at v_h_max.
        max_vel = min(max_vel, float(self.safety_config.ssm.v_h_max))
        if self._human_pelvis_id is not None:
            self._prev_human_pos = data.xpos[self._human_pelvis_id].copy()
            self._prev_sim_time = data.time
        return np.stack(positions), names, max_vel

    def _on_step(self):
        """Called after step - log violations if configured."""
        super()._on_step()
        
        if self._step_safety_info is None:
            return
        
        if self.safety_config.log_violations:
            if self._step_safety_info.ssm_violation:
                required_sep = self._step_safety_info.min_separation - self._step_safety_info.ssm_margin
                logger.warning(
                    f"SSM Violation! Distance: {self._step_safety_info.min_separation:.2f}m, "
                    f"Required: {required_sep:.2f}m, Margin: {self._step_safety_info.ssm_margin:.3f}m"
                )
            if self._step_safety_info.pfl_violation:
                logger.warning(
                    f"PFL Violation! Force: {self._step_safety_info.max_contact_force:.1f}N "
                    f"on {self._step_safety_info.contact_region}"
                )
    
    def _reward(self) -> float:
        """Get reward with optional violation penalty and workspace shaping."""
        base_reward = super()._reward()

        if self.safety_config.add_violation_penalty and self._step_safety_info:
            if self._step_safety_info.ssm_violation or self._step_safety_info.pfl_violation:
                base_reward -= self.safety_config.violation_penalty

        if self.safety_config.add_workspace_penalty:
            base_reward += self._compute_workspace_penalty()

        return base_reward

    def _compute_workspace_penalty(self) -> float:
        """Phase 3 workspace shaping: r_workspace = -beta * max(0, ||p_ee - p_task|| - r_ws).

        Reuses :meth:`_get_robot_state` so the EE-position lookup goes through
        the same fallback chain used for IK: prefer ``self._robot.get_ee_position()``
        when the robot exposes it, otherwise pick up ``state["link_pos"]["ee"]``
        which the helper populates via :data:`_ROBOT_LINK_NAMES` mj_name2id
        lookups. H1 (the default robot) has no ``get_ee_position`` method, so
        the ``link_pos`` fallback is the load-bearing path. Returns 0 silently
        when either position is unavailable (e.g. a task with no manipulable
        and a robot mid-rebind).
        """
        state = self._get_robot_state()
        ee_pos = state.get("ee_pos")
        if ee_pos is None:
            link_pos = state.get("link_pos") or {}
            ee_pos = link_pos.get("ee")
        if ee_pos is None:
            return 0.0

        task_pos = state.get("task_object_pos")
        if task_pos is None:
            return 0.0

        dist = float(np.linalg.norm(np.asarray(ee_pos, dtype=float) - task_pos))
        excess = max(0.0, dist - self.safety_config.workspace_radius)
        # Bound the per-step penalty at -beta*cap so the discounted return stays
        # inside the critic's value support (see SafetyConfig.workspace_excess_cap).
        cap = self.safety_config.workspace_excess_cap
        if cap is not None:
            excess = min(excess, float(cap))
        return -self.safety_config.workspace_beta * excess

    def step(self, action):
        """Step environment and add privileged info."""
        obs, reward, done, truncated, info = super().step(action)
        
        # Add human motion phase to info
        if self.human_controller is not None:
            info["human_phase"] = self.human_controller.current_phase
        
        # Add privileged info for SafePolicy
        try:
            # Get joint positions for freezing/retreat behavior
            # Need to use ACTUATED joint positions to match action space
            if hasattr(self._robot, "qpos_actuated"):
                qpos = self._robot.qpos_actuated
            elif hasattr(self._robot, "get_joint_positions"):
                qpos = self._robot.get_joint_positions()
            elif hasattr(self._robot, "qpos"):
                qpos = self._robot.qpos
            else:
                qpos = None
                
            if qpos is not None:
                if "safety" not in info:
                    info["safety"] = {}
                info["safety"]["qpos"] = qpos
        except Exception:
            pass
            
        return obs, reward, done, truncated, info
    
    @property
    def terminate(self) -> bool:
        """Check termination including safety violations."""
        base_terminate = super().terminate
        
        if self.safety_config.terminate_on_violation and self._step_safety_info:
            if self._step_safety_info.ssm_violation or self._step_safety_info.pfl_violation:
                return True
        
        return base_terminate
    
    def get_info(self) -> Dict[str, Any]:
        """Get info dict including safety information."""
        info = super().get_info()
        
        if self._step_safety_info is not None:
            info["safety"] = self._step_safety_info.to_dict()
        else:
            info["safety"] = {}
        
        # Add current scenario info
        if self._current_scenario is not None:
            info["scenario"] = {
                "disruption_type": self._current_scenario.disruption_type.name,
                "trigger_time": self._current_scenario.trigger_time,
            }
        
        return info


def make_safety_env(
    task_cls: type,
    action_mode: ActionMode,
    safety_config: Optional[SafetyConfig] = None,
    human_config: Optional[HumanConfig] = None,
    scenario_sampler: Optional[ScenarioSampler] = None,
    inject_human: bool = True,
    **kwargs,
) -> SafetyBiGymEnv:
    """
    Create a SafetyBiGymEnv for any BiGym task.

    Dynamically creates a class that inherits from both SafetyBiGymEnv and
    the given BiGym task class, so you get the task's scene + safety monitoring.

    Example::

        from bigym.envs.reach_target import ReachTargetSingle
        from bigym.envs.pick_and_place import PickBox

        env = make_safety_env(ReachTargetSingle, action_mode=..., human_config=...)
        env = make_safety_env(PickBox, action_mode=..., inject_human=True)

    Args:
        task_cls: A BiGym task class (e.g. ReachTargetSingle, PickBox).
                  Pass BiGymEnv for the default empty scene.
        action_mode: BiGym action mode for robot control.
        safety_config: ISO 15066 safety parameters.
        human_config: Human spawn and motion configuration.
        scenario_sampler: Sampler for diverse scenarios.
        inject_human: Whether to inject human into scene.
        **kwargs: Extra arguments forwarded to the task class __init__.

    Returns:
        An environment instance with both task behaviour and safety monitoring.
    """
    # Create a combined class: SafetyBiGymEnv first (overrides step/reset),
    # then task_cls (provides scene setup and reward).
    cls_name = f"Safety{task_cls.__name__}"
    combined_cls = type(cls_name, (SafetyBiGymEnv, task_cls), {})

    return combined_cls(
        action_mode=action_mode,
        safety_config=safety_config,
        human_config=human_config,
        scenario_sampler=scenario_sampler,
        inject_human=inject_human,
        **kwargs,
    )
