#!/usr/bin/env python
"""Aggregate the E4.1 (P5) per-row benchmark CSVs into the headline LaTeX table.

Reads the per-row CSVs written by ``scripts/run_e4_1_headline.sh`` (one
``benchmark_policy.py`` invocation per row, schema = ``benchmark.schema.COLUMNS``)
and emits Table~\\ref{tab:e4.1-feature-incremental}: one row per configuration with
the headline proximity-violation axis (+ bootstrap CI), task metrics, and — for
the filtered rows — the filter intervention / passthrough rates.

Pure stdlib (csv only), so it runs anywhere and is unit-testable without the
benchmark's pandas/pyarrow stack. The lowest proximity-violation row is bolded.

Usage:
  python scripts/aggregate_e4_1.py --in-dir results/e4_1/<run_tag> \
      --out report_tables/e4.1_feature_incremental.tex
  # or explicit files:
  python scripts/aggregate_e4_1.py --rows row1_baseline=a.csv row5_hybrid=b.csv --out tbl.tex
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# (csv basename stem, human label) in table order — the feature-incremental rows.
# run_e4_1_headline.sh evaluates the whole table on one obs mode (default noisy).
ROWS: List[Tuple[str, str]] = [
    ("row1_baseline", "Unconstrained baseline"),
    ("row2_workspace", r"\quad + Workspace shaping"),
    ("row3_lagrangian", r"\quad + Lagrangian (cont.\ cost)"),
    ("row4_baseline_filter", "Baseline + runtime filter"),
    ("row5_hybrid", "Full hybrid"),
]


def read_last_row(path: Path) -> Optional[Dict[str, str]]:
    """Return the last data row of a benchmark CSV (it appends one row per run)."""
    if not path.is_file():
        return None
    with path.open(newline="") as fh:
        rows = list(csv.DictReader(fh))
    return rows[-1] if rows else None


def _f(row: Dict[str, str], key: str) -> Optional[float]:
    v = row.get(key, "")
    if v is None or str(v).strip() == "":
        return None
    try:
        return float(v)
    except ValueError:
        return None


def fmt_ci(row: Dict[str, str], key: str, scale: float = 1.0, prec: int = 3) -> str:
    """``mean [lo, hi]`` from ``key`` / ``key_ci_lo`` / ``key_ci_hi``; ``--`` if absent."""
    m = _f(row, key)
    if m is None:
        return "--"
    lo, hi = _f(row, f"{key}_ci_lo"), _f(row, f"{key}_ci_hi")
    s = f"{m * scale:.{prec}f}"
    if lo is not None and hi is not None:
        s += f"\\,{{\\footnotesize[{lo * scale:.{prec}f}, {hi * scale:.{prec}f}]}}"
    return s


def fmt_val(row: Dict[str, str], key: str, prec: int = 3) -> str:
    m = _f(row, key)
    return "--" if m is None else f"{m:.{prec}f}"


def build_table(rows: Dict[str, Dict[str, str]], caption: str, label: str) -> str:
    present = [(stem, lab) for stem, lab in ROWS if stem in rows]
    if not present:
        raise SystemExit("No E4.1 row CSVs found — nothing to aggregate.")

    # Bold the lowest proximity-violation rate among the present rows.
    prox = {s: _f(rows[s], "ep_proximity_violation_rate") for s, _ in present}
    prox = {s: v for s, v in prox.items() if v is not None}
    best = min(prox, key=prox.get) if prox else None

    out: List[str] = []
    out.append(r"% Auto-generated by scripts/aggregate_e4_1.py — do not edit by hand.")
    out.append(r"\begin{table}[t]")
    out.append(r"  \centering")
    out.append(rf"  \caption{{{caption}}}")
    out.append(rf"  \label{{{label}}}")
    out.append(r"  \begin{tabular}{lccccc}")
    out.append(r"    \toprule")
    out.append(
        r"    Configuration & Prox.\ viol.\ $\downarrow$ & Success $\uparrow$ "
        r"& Reward & Steps & Interv.\ / Passth. \\"
    )
    out.append(r"    \midrule")
    for stem, lab in present:
        r = rows[stem]
        prox_cell = fmt_ci(r, "ep_proximity_violation_rate")
        if stem == best:
            prox_cell = rf"\textbf{{{prox_cell}}}"
        succ = fmt_ci(r, "success_rate")
        reward = fmt_val(r, "episode_reward_mean")
        steps = fmt_ci(r, "steps_to_completion", prec=1)
        interv = _f(r, "filter_intervention_rate")
        if interv is None:
            filt_cell = "--"
        else:
            passth = _f(r, "filter_passthrough_rate")
            p = f"{passth:.3f}" if passth is not None else f"{1.0 - interv:.3f}"
            filt_cell = f"{interv:.3f} / {p}"
        out.append(f"    {lab} & {prox_cell} & {succ} & {reward} & {steps} & {filt_cell} \\\\")
    out.append(r"    \bottomrule")
    out.append(r"  \end{tabular}")
    out.append(r"\end{table}")
    return "\n".join(out) + "\n"


def parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--in-dir", type=Path, default=None,
                   help="Directory of per-row CSVs (row1_baseline.csv, ...).")
    p.add_argument("--rows", nargs="*", default=[], metavar="STEM=PATH",
                   help="Explicit stem=path pairs; override/augment --in-dir.")
    p.add_argument("--out", type=Path, default=None, help="Write LaTeX here (also prints).")
    p.add_argument("--caption", default="Feature-incremental safety/task comparison on "
                   "\\texttt{saucepan\\_to\\_hob} under \\texttt{coworker\\_train} "
                   "(G1 coworker). Proximity at $\\tau=0.3$\\,m; 95\\% bootstrap CIs.")
    p.add_argument("--label", default="tab:e4.1-feature-incremental")
    return p.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    rows: Dict[str, Dict[str, str]] = {}
    if args.in_dir is not None:
        for stem, _ in ROWS:
            r = read_last_row(args.in_dir / f"{stem}.csv")
            if r is not None:
                rows[stem] = r
    for pair in args.rows:
        if "=" not in pair:
            raise SystemExit(f"--rows expects STEM=PATH; got {pair!r}")
        stem, _, path = pair.partition("=")
        r = read_last_row(Path(path))
        if r is not None:
            rows[stem] = r
    if not rows:
        raise SystemExit("No CSVs read — pass --in-dir <dir> or --rows STEM=PATH ...")

    table = build_table(rows, args.caption, args.label)
    found = [s for s, _ in ROWS if s in rows]
    missing = [s for s, _ in ROWS if s not in rows]
    sys.stderr.write(f"rows found: {found}\n")
    if missing:
        sys.stderr.write(f"rows missing (skipped): {missing}\n")
    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(table)
        sys.stderr.write(f"wrote {args.out}\n")
    sys.stdout.write(table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
