#!/usr/bin/env python
"""Aggregate the E4.1 (P5) per-row benchmark CSVs into the E5.1 tail-risk LaTeX
table — CVaR_0.95 and worst-case columns the benchmark already emits over the
pooled (seed x episode) rolls. Pure stdlib; same row layout as aggregate_e4_1.py.

Usage:
  python scripts/aggregate_e5_1.py --in-dir results/e4_1/<noisy_run_tag> \
      --out report_tables/e5.1_tail.tex
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Same rows as aggregate_e4_1.py (the feature-incremental configs).
ROWS: List[Tuple[str, str]] = [
    ("row1_baseline", "Unconstrained baseline"),
    ("row2_workspace", r"\quad + Workspace shaping"),
    ("row3_lagrangian", r"\quad + Lagrangian (cont.\ cost)"),
    ("row4_baseline_filter", "Baseline + runtime filter"),
    ("row5_hybrid", "Full hybrid"),
]


def read_last_row(path: Path) -> Optional[Dict[str, str]]:
    if not path.is_file():
        return None
    with path.open(newline="") as fh:
        rows = list(csv.DictReader(fh))
    return rows[-1] if rows else None


def _f(row: Dict[str, str], key: str) -> Optional[float]:
    v = row.get(key, "")
    if v is None or str(v).strip() == "":
        return None
    try:
        return float(v)
    except ValueError:
        return None


def fmt(row: Dict[str, str], key: str, prec: int = 3) -> str:
    v = _f(row, key)
    return "--" if v is None else f"{v:.{prec}f}"


def build_table(rows: Dict[str, Dict[str, str]], caption: str, label: str) -> str:
    present = [(stem, lab) for stem, lab in ROWS if stem in rows]
    if not present:
        raise SystemExit("No E4.1 row CSVs found — nothing to aggregate.")
    out: List[str] = []
    out.append(r"% Auto-generated by scripts/aggregate_e5_1.py — do not edit by hand.")
    out.append(r"\begin{table}[t]")
    out.append(r"  \centering")
    out.append(rf"  \caption{{{caption}}}")
    out.append(rf"  \label{{{label}}}")
    out.append(r"  \begin{tabular}{lcccc}")
    out.append(r"    \toprule")
    out.append(
        r"    Configuration & $\cvar_{0.95}$ cost $\downarrow$ "
        r"& $\cvar_{0.95}$ min-sep (m) $\uparrow$ & p5 min-sep (m) $\uparrow$ "
        r"& worst min-sep (m) $\uparrow$ \\"
    )
    out.append(r"    \midrule")
    for stem, lab in present:
        r = rows[stem]
        out.append(
            f"    {lab} & {fmt(r, 'cvar95_ep_cost_integral', 2)} "
            f"& {fmt(r, 'cvar95_ep_min_separation')} "
            f"& {fmt(r, 'p5_ep_min_separation')} "
            f"& {fmt(r, 'ep_min_separation_lowest')} \\\\"
        )
    out.append(r"    \bottomrule")
    out.append(r"  \end{tabular}")
    out.append(r"\end{table}")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--in-dir", type=Path, required=True, help="Dir of per-row E4.1 CSVs.")
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--caption", default="Tail-risk on \\texttt{saucepan\\_to\\_hob} / "
                    "\\texttt{coworker\\_train} (G1, \\texttt{noisy}): $\\cvar_{0.95}$ and "
                    "worst-case over the pooled seed$\\times$episode rolls.")
    ap.add_argument("--label", default="tab:e5.1-tail")
    args = ap.parse_args(argv)

    rows: Dict[str, Dict[str, str]] = {}
    for stem, _ in ROWS:
        r = read_last_row(args.in_dir / f"{stem}.csv")
        if r is not None:
            rows[stem] = r
    if not rows:
        raise SystemExit(f"No row CSVs under {args.in_dir}.")

    table = build_table(rows, args.caption, args.label)
    sys.stderr.write(f"rows found: {[s for s, _ in ROWS if s in rows]}\n")
    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(table)
        sys.stderr.write(f"wrote {args.out}\n")
    sys.stdout.write(table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
