"""Single source of truth for Unitree G1 humanoid constants.

The G1 plays the "coworker" role that SMPL-H used to fill (asset:
``safety_bigym/assets/g1_human_body.xml``, generated by
``scripts/build_g1_human_body.py`` from the upstream Unitree menagerie model).
Every G1-aware module (controller, IK, env wrapper) imports its names and
ranges from here so a model revision is a one-file edit.

Design contract (matches SMPL-H integration points in ``safety_env.py``):

- The root body is renamed to ``Pelvis`` and marked ``mocap="true"`` so the
  trajectory planner can teleport it via ``data.mocap_pos`` / ``data.mocap_quat``.
- The 29 body joints are hinge joints; the build script regenerates the
  ``<actuator>`` block with one ``position`` actuator per joint
  (``class="position_actuator"``, kp=200 kv=20 to match SMPL-H PD gains).
- The 14 SSM bodies listed here are the closest-joint distance samples used by
  ``ISO15066Wrapper.compute_ssm``. Names exist in the generated MJCF.
- Arm chains drive procedural reach IK during the COWORKER disruption.
"""

from __future__ import annotations

# Mocap root body name (was "Pelvis" for SMPL-H; we rename the G1 ``pelvis``
# to match so existing env / IK / controller code finds it without dispatch.)
PELVIS_BODY = "Pelvis"

# Standing pelvis height (m). Chosen to put G1's feet roughly on the floor and
# the trunk near where SMPL-H ends up after AMASS standing frames. Tunable via
# ``HumanConfig.g1_standing_pelvis_z``.
STANDING_PELVIS_Z = 0.95

# 29 actuated joints in upstream g1.xml order. This is the *qpos* order
# (after stripping the 7-element freejoint prefix) and the *ctrl* order
# the upstream ``stand`` keyframe uses. Drives the controller's joint→qpos
# mapping and the PD target buffer.
BODY_JOINT_NAMES = [
    # Left leg (6)
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    # Right leg (6)
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
    # Waist (3)
    "waist_yaw_joint",
    "waist_roll_joint",
    "waist_pitch_joint",
    # Left arm (7)
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_roll_joint",
    "left_wrist_pitch_joint",
    "left_wrist_yaw_joint",
    # Right arm (7)
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_roll_joint",
    "right_wrist_pitch_joint",
    "right_wrist_yaw_joint",
]

# Standing-pose joint angles (rad), from the upstream ``stand`` keyframe
# (qpos slots [7:36], stripping the freejoint prefix). Joints not listed
# default to 0. Slightly abducted shoulders + bent elbows.
STANDING_POSE = {
    "left_shoulder_pitch_joint": 0.2,
    "left_shoulder_roll_joint": 0.2,
    "left_elbow_joint": 1.28,
    "right_shoulder_pitch_joint": 0.2,
    "right_shoulder_roll_joint": -0.2,
    "right_elbow_joint": 1.28,
}

# Bodies sampled for ISO 15066 closest-joint Speed & Separation Monitoring.
# 14 bodies spanning the G1 envelope: trunk, both legs (hip / knee / ankle),
# both arms (shoulder / elbow / wrist). All exist in the generated MJCF.
SSM_BODY_NAMES = [
    "Pelvis",
    "torso_link",
    "left_hip_yaw_link", "right_hip_yaw_link",
    "left_knee_link", "right_knee_link",
    "left_ankle_roll_link", "right_ankle_roll_link",
    "left_shoulder_roll_link", "right_shoulder_roll_link",
    "left_elbow_link", "right_elbow_link",
    "left_wrist_yaw_link", "right_wrist_yaw_link",
]

# Procedural reach-IK arm chains. Shoulder (3 DoF) + elbow (1 DoF) + wrist
# (3 DoF) is the full 7-DoF chain; the IK solver may freeze the wrist on
# unsolvable targets. End-effector is the wrist-yaw link (where the rubber
# hand visual attaches in the upstream MJCF).
ARM_CHAINS = {
    "right_arm": {
        "joints": [
            "right_shoulder_pitch_joint",
            "right_shoulder_roll_joint",
            "right_shoulder_yaw_joint",
            "right_elbow_joint",
            "right_wrist_roll_joint",
            "right_wrist_pitch_joint",
            "right_wrist_yaw_joint",
        ],
        "end_effector": "right_wrist_yaw_link",
        "shoulder_body": "right_shoulder_pitch_link",
    },
    "left_arm": {
        "joints": [
            "left_shoulder_pitch_joint",
            "left_shoulder_roll_joint",
            "left_shoulder_yaw_joint",
            "left_elbow_joint",
            "left_wrist_roll_joint",
            "left_wrist_pitch_joint",
            "left_wrist_yaw_joint",
        ],
        "end_effector": "left_wrist_yaw_link",
        "shoulder_body": "left_shoulder_pitch_link",
    },
}


def standing_qpos(model) -> "object":
    """Return a full qpos buffer with body joints at the standing pose.

    Joints not in ``STANDING_POSE`` default to 0. The pelvis (mocap body)
    contributes nothing to qpos. Imported lazily to keep this module
    dependency-free for the spec import path.
    """
    import numpy as np
    import mujoco

    qpos = np.zeros(model.nq)
    for joint_name, angle in STANDING_POSE.items():
        jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, joint_name)
        if jid >= 0:
            qpos[model.jnt_qposadr[jid]] = angle
    return qpos
