"""Single source of truth for Unitree G1 skeleton constants.

The G1 humanoid plays the "coworker" role that the SMPL-H human used to fill
(see ``assets/g1_human_body.xml``, generated by
``scripts/build_g1_human_body.py``). Every module that needs G1 joint/body
names — the controller, the reach IK, the coworker behaviour, the env's SSM
body list — imports them from here so a model change only touches one file.

The G1 is driven kinematically: the ``pelvis`` is a mocap body teleported
along the scripted COWORKER trajectory, while the 29 body joints are PD-held to
a fixed standing pose (the menagerie ``stand`` keyframe). There is no AMASS /
walking gait.
"""

from __future__ import annotations

# Mocap root body name (was "Pelvis" for SMPL-H).
PELVIS_BODY = "pelvis"

# Standing pelvis height (m) — from the menagerie `stand` keyframe. Used as the
# fixed mocap Z so the feet sit roughly on the floor.
STANDING_PELVIS_Z = 0.793

# All 29 actuated joints, in model (qpos) order. Drives the controller's
# joint->qpos mapping and the PD target buffer.
BODY_JOINT_NAMES = [
    "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint",
    "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
    "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",
    "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
    "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint",
    "left_shoulder_pitch_joint", "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint", "left_elbow_joint",
    "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint", "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint", "right_elbow_joint",
    "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint",
]

# Standing-pose joint angles (rad). Joints omitted here default to 0. Matches
# the menagerie `stand` keyframe: a relaxed stance with slightly abducted
# shoulders and bent elbows.
STANDING_POSE = {
    "left_shoulder_pitch_joint": 0.2,
    "left_shoulder_roll_joint": 0.2,
    "left_elbow_joint": 1.28,
    "right_shoulder_pitch_joint": 0.2,
    "right_shoulder_roll_joint": -0.2,
    "right_elbow_joint": 1.28,
}

# Bodies tracked for ISO 15066 Speed & Separation Monitoring (closest-joint
# distance). Chosen to span the G1 envelope: trunk, both legs, both arms.
SSM_BODY_NAMES = [
    "pelvis", "torso_link",
    "left_hip_yaw_link", "right_hip_yaw_link",
    "left_knee_link", "right_knee_link",
    "left_ankle_roll_link", "right_ankle_roll_link",
    "left_shoulder_roll_link", "right_shoulder_roll_link",
    "left_elbow_link", "right_elbow_link",
    "left_wrist_yaw_link", "right_wrist_yaw_link",
]

# Reach-IK arm chains. Shoulder (3 DoF) + elbow (1 DoF) is enough to place the
# hand at a 3D target; the wrists are left PD-held at rest. The end-effector
# body is the last arm link (≈ the hand).
ARM_CHAINS = {
    "right_arm": {
        "joints": [
            "right_shoulder_pitch_joint", "right_shoulder_roll_joint",
            "right_shoulder_yaw_joint", "right_elbow_joint",
        ],
        "end_effector": "right_wrist_yaw_link",
        "shoulder_body": "right_shoulder_pitch_link",
    },
    "left_arm": {
        "joints": [
            "left_shoulder_pitch_joint", "left_shoulder_roll_joint",
            "left_shoulder_yaw_joint", "left_elbow_joint",
        ],
        "end_effector": "left_wrist_yaw_link",
        "shoulder_body": "left_shoulder_pitch_link",
    },
}


def standing_qpos(model) -> "object":
    """Return a full-sized qpos buffer set to the G1 standing pose.

    Joints not in ``STANDING_POSE`` are left at 0. Requires a loaded
    ``mujoco.MjModel``; imported lazily to keep this module dependency-free.
    """
    import numpy as np
    import mujoco

    qpos = np.zeros(model.nq)
    for jn, angle in STANDING_POSE.items():
        jid = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, jn)
        if jid >= 0:
            qpos[model.jnt_qposadr[jid]] = angle
    return qpos
